// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Hardcoded fallbacks so the client works in dev mode (Vite dev server does not
// load .env.production, only .env / .env.local / .env.development).
// These values are already committed in .env.production so they are not secret.
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  'https://wdvsfjpkxfjaelrydgqd.supabase.co';

const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkdnNmanBreGZqYWVscnlkZ3FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3OTg0MTQsImV4cCI6MjA5MDM3NDQxNH0.Xh-9eTBJGgQf_9Ry0WCw2qAW5X_qEBdzyuZDVGbcjUg';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);